export const USER_RESPONSES = {
  // REGISTER
  USER_ALREADY_EXISTS: '400_USER_ALREADY_EXISTS',
  USER_DEFAULTS_CREATION_FAILED: '400_USER_DEFAULTS_CREATION_FAILED',
  // ACCESS
  USER_ACCESS_FAILED: '400_USER_ACCESS_FAILED',
  USER_NOT_FOUND: '404_USER_NOT_FOUND',
  // USER PROFILE
  USER_GET_FAILED: '400_USER_GET_FAILED',
  // UPDATE PROFILE
  USER_PROFILE_UPDATE_FAILED: '400_USER_PROFILE_UPDATE_FAILED',
  // UPDATE PRIVACY
  USER_PRIVACY_UPDATE_FAILED: '400_USER_PRIVACY_UPDATE_FAILED',
};
