export const COLLECTIONS_RESPONSES = {
  COLLECTION_CREATE_FAILED: '400_COLLECTION_CREATE_FAILED',
  COLLECTION_GET_FAILED: '400_COLLECTION_GET_FAILED',
  COLLECTION_UPDATE_FAILED: '400_COLLECTION_UPDATE_FAILED',
  COLLECTION_DELETE_FAILED: '400_COLLECTION_DELETE_FAILED',
  // add game to collection
  COLLECTION_ADD_GAME_FAILED: '400_COLLECTION_ADD_GAME_FAILED',
  COLLECTION_FAVORITE_GAME_FAILED: '400_COLLECTION_FAVORITE_GAME_FAILED',
  COLLECTION_SET_GAME_STATUS_FAILED: '400_COLLECTION_SET_GAME_STATUS_FAILED',
  COLLECTION_GAME_ALREADY_ADDED: '400_COLLECTION_GAME_ALREADY_ADDED',
  COLLECTION_INVALID_TYPE: '400_COLLECTION_INVALID_TYPE',
  COLLECTION_ID_REQUIRED: '400_COLLECTION_ID_REQUIRED',
};
