export const COLLECTIONS_RESPONSES = {
  COLLECTION_CREATE_FAILED: '400_COLLECTION_CREATE_FAILED',
  COLLECTION_GET_FAILED: '400_COLLECTION_GET_FAILED',
  COLLECTION_UPDATE_FAILED: '400_COLLECTION_UPDATE_FAILED',
};
